### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [Jan--Henrik/EF-S-Adapter#1]
Hello!

I found link to this project from https://hackaday.com/2020/10/24/proprietary-lenses-are-no-problem-with-this-usb-adaptor/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by Jana-Marie** [comment]
Thank you for your input, I've added a license. :)

**Comment by vazhnov** [comment]
MIT — great!
Thank you very much!
